version: '3.8'
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu
    tty: true
#    platform: linux/arm64/v8
    volumes:
      - .:/root/dotfiles
    privileged: true
