ln -s ~/dotfiles/.Brewfile ~/.Brewfile
ln -s ~/dotfiles/fish/ ~/.config/fish
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
ln -s ~/dotfiles/.leaf.d ~/.emacs.d
ln -s ~/dotfiles/.tmux ~/.tmux
ln -s ~/dotfiles/.tmux.conf ~/.tmux.conf
ln -s ~/dotfiles/.ssh ~/.ssh
ln -s ~/dotfiles/.gitignore_global ~/.gitignore_global
ln -s ~/dotfiles/.gitconfig ~/.gitconfig
